### ISSUE TITLE
在非root用户，用systemctl自动启动p2t serve会出现[Errno 13] Permission denied: 'output-md-root'

### ISSUE THREAD

**Issue by realDGD** [breezedeus/Pix2Text#101]
手动在终端输入该指令启动，与以root用户身份用systemctl自动启动都不会出现这种情况，均可正常使用，可能跟serve.py有关。

设备：Ubuntu 24.04 LTS Linux 

环境：Anaconda Python 3.11.7

重复率：必现

**Comment by breezedeus** [comment]
这不就是你没权限建文件夹么，你用 `-o` 传一个有权限的地方就好了吧。https://pix2text.readthedocs.io/zh/latest/command

**Comment by realDGD** [comment]
> 这不就是你没权限建文件夹么，你用 `-o` 传一个有权限的地方就好了吧。https://pix2text.readthedocs.io/zh/latest/command

感谢，问题解决
