### ISSUE TITLE
公式图片的背景色是透明色，无法识别公式

### ISSUE THREAD

**Issue by evanlin88** [breezedeus/Pix2Text#102]
样本：[样本.zip](https://github.com/breezedeus/Pix2Text/files/15260788/default.zip)
执行效果：
![20240509-180539](https://github.com/breezedeus/Pix2Text/assets/154392846/a5ff57c0-3911-4b67-b00e-fbd8000801cf)

**Comment by breezedeus** [comment]
嗯。可以转成白底的 jpg。训练集里没什么 png
