### ISSUE TITLE
关于模型评估过程中的标准化操作

### ISSUE THREAD

**Issue by Sanster** [breezedeus/Pix2Text#104]
<img width="783" alt="image" src="https://github.com/breezedeus/Pix2Text/assets/3998421/61498cb3-3df9-43f7-8f12-1be5c12827e0">

在新版公式识别的 blog 中提到了计算 CER 前会对标注和模型结果进行标准化，目前我也在做这方面的评估，采用了以下的标准化操作，但是不确定这些操作是否足够，想请教一下还有没有其它的标准化操作能够提高测试指标的准确程度？

- 去除空格符号 `[r"\ ", r"\quad", r"\,", r"\;", r"\:", r"\!", " "]`
- 统一 environment： 例如 "equation", "align", "align*", "gathered", "$$", "\[", "\]" 等

**Comment by Sanster** [comment]
对比了 pix2text 和 [TexTeller](https://github.com/OleehyO/TexTeller) 的模型，pix2text 模型小很多，效果却好很多 👍

**Comment by breezedeus** [comment]
Latex 表达式的标准化挺复杂的。可以参考：https://github.com/harvardnlp/im2markup
