### ISSUE TITLE
开源模型无法识别斜的场景

### ISSUE THREAD

**Issue by evanlin88** [breezedeus/Pix2Text#110]
![20240522-185729](https://github.com/breezedeus/Pix2Text/assets/154392846/28eefdb2-49ac-440d-b2e5-de66548c73a2)
若图片是正常摆正，则开源版本也能识别；另外网页版也正常，是否开源版不支持识别斜的文字公式？

**Comment by breezedeus** [comment]
没这个差别，应该只是模型效果带来的差异。

**Comment by evanlin88** [comment]
我重新选了一些其他斜的图片，因为切图原因，会存在类似的，我用网页版验证，好像也有点问题；是否模型样本不足到导致的？如：
![微信图片_20240524103254](https://github.com/breezedeus/Pix2Text/assets/154392846/a58ee707-8799-451a-a0ca-69679a6f3430)
![微信截图_20240524145041](https://github.com/breezedeus/Pix2Text/assets/154392846/2ef02fd1-c214-4da6-abd3-cfe5e20e86d4)
