### ISSUE TITLE
配置layout_parser时在config中传入root在方法中报错

### ISSUE THREAD

**Issue by AILock** [breezedeus/Pix2Text#116]
pix_to_text.py 第57行 layout_parser = DocXLayoutParser.from_config(None, device=device)

@classmethod
    def from_config(cls, configs: Optional[dict] = None, device: str = None, **kwargs):
        configs = configs or {}
        device = select_device(device)
        # configs['device'] = device if device != 'mps' else 'cpu'

        return cls(
            device=device,
            model_fp=configs.get('model_fp', None),
            root=configs.get('root', data_dir()),
            **configs,
        )

在return时configs存在root初始化会报错，希望修改下
@classmethod
    def from_config(cls, configs: Optional[dict] = None, device: str = None, **kwargs):
        configs = configs or {}
        device = select_device(device)
        # configs['device'] = device if device != 'mps' else 'cpu'
        configs["root"] = configs.get('root', data_dir())
        configs["model_fp"] = configs.get('model_fp', None)
        return cls(
            device=device,
            **configs,
        )

**Comment by breezedeus** [comment]
看看你的版本是否是最新版

**Comment by AILock** [comment]
> 看看你的版本是否是最新版

main分支代码路径是pix2text.doc_xl_layout.doc_xl_layout_parser.DocXLayoutParser.from_config

**Comment by breezedeus** [comment]
v1.1.1.2 已修复，感谢
