### ISSUE TITLE
Missing files in the AppData\Roaming\pix2text\1.1 folder

### ISSUE THREAD

**Issue by paragasd** [breezedeus/Pix2Text#122]
I was testing the `from_config()` method and ran into this error: 
```
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Thomas Bertans\\AppData\\Roaming\\pix2text\\1.1\\layout-parser\\DocXLayout_231012.pth'
```
which seems to indicate that the specified file doesn't exist. 

I ended up checking the `AppData\Roaming\pix2text\1.1` folder, only to find it completely empty. I tried reinstalling the pix2text package using both
```
pip install pix2text
```
and
```
pip install pix2text -i https://mirrors.aliyun.com/pypi/simple
```
but the folder still remains empty. 

Is there any way to fill the `AppData\Roaming\pix2text\1.1` folder or the `AppData\Roaming\pix2text` folder with the correct files?

**Comment by breezedeus** [comment]
Do not terminate the run manually, the models will be downloaded automatically. See https://pix2text.readthedocs.io/zh-cn/stable/models/ for more instructions.
