### ISSUE TITLE
Unable to use GPU / CUDA for prediction

### ISSUE THREAD

**Issue by breezyChedi** [breezedeus/Pix2Text#132]
I have the following error while attempting to run the command `p2t predict -l en -d cuda --resized-shape 1550 -i input-photos -o output-md-gang --save-debug-res output-debug-gang`

error: `ValueError: Asked to use CUDAExecutionProvider as an ONNX Runtime execution provider, but the available execution providers are ['AzureExecutionProvider', 'CPUExecutionProvider'].`

**Comment by breezedeus** [comment]
uninstall onnxruntime, install onnxruntime-gpu

**Comment by breezyChedi** [comment]
> uninstall onnxruntime, install onnxruntime-gpu
latex_ocr.py still requires optimum.onnxruntime so uninstalling results in an error aswell.
