### ISSUE TITLE
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### ISSUE THREAD

**Issue by Espacio-root** [breezedeus/Pix2Text#135]
Error shows up when executing
`pix2tex --gui`

Output:
Sandboxing disabled by user.
Path override failed for key base::DIR_APP_DICTIONARIES and path '/home/espacio/.conda/envs/machine-learning/bin/qtwebengine_dictionaries'
Path override failed for key base::DIR_APP_DICTIONARIES and path '/home/espacio/.conda/envs/machine-learning/lib/python3.12/site-packages/PyQt6/Qt6/libexec/qtwebengine_dictionaries'
Path override failed for key base::DIR_APP_DICTIONARIES and path '/home/espacio/.conda/envs/machine-learning/lib/python3.12/site-packages/PyQt6/Qt6/libexec/qtwebengine_dictionaries'
The cached device pixel ratio value was stale on window update.  Please file a QTBUG which explains how to reproduce.
Traceback (most recent call last):
  File "/home/espacio/.conda/envs/machine-learning/lib/python3.12/site-packages/pix2tex/gui.py", line 227, in run
    prediction = self.model(self.img)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/home/espacio/.conda/envs/machine-learning/lib/python3.12/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/espacio/.conda/envs/machine-learning/lib/python3.12/site-packages/pix2tex/cli.py", line 115, in __call__
    img = minmax_size(pad(img), self.args.max_dimensions, self.args.min_dimensions)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/espacio/.conda/envs/machine-learning/lib/python3.12/site-packages/pix2tex/cli.py", line 47, in minmax_size
    img = img.resize(size.astype(int), Image.BILINEAR)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/espacio/.conda/envs/machine-learning/lib/python3.12/site-packages/PIL/Image.py", line 2297, in resize
    if self.size == size and box == (0, 0) + self.size:
       ^^^^^^^^^^^^^^^^^
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
The cached device pixel ratio value was stale on window update.  Please file a QTBUG which explains how to reproduce.
The cached device pixel ratio value was stale on window update.  Please file a QTBUG which explains how to reproduce.

OS:
Arch Linux + Hyprland (wayland)

**Comment by breezedeus** [comment]
Hi, I think you've got the package name wrong, the package name is pix2text and the package you've got wrong is pix2tex.
