### ISSUE TITLE
关于生成LaTeX的公式的可读性问题

### ISSUE THREAD

**Issue by realDGD** [breezedeus/Pix2Text#136]
尊敬的开发者您好，感谢您开发了如此功能的应用，以下是我使用该软件的问题。

# 问题
<img width="326" alt="截图_20240802094009" src="https://github.com/user-attachments/assets/1fd716cd-308a-4e51-af71-e194d6640092">

如图该公式，用Pix2Text的话生成的为`\mathbf{m}=\operatorname{s i n} \theta( \rho) \, \operatorname{c o s} \phi_{0} \, \hat{\rho}+\operatorname{s i n} \theta( \rho) \, \operatorname{s i n} \phi_{0} \, \hat{\phi}+\operatorname{c o s} \theta( \rho) \, \hat{z}`

实际上，可以简化为`\mathbf{m} = \sin \theta(\rho) \cos \phi_{0} \hat{\rho} + \sin \theta(\rho) \sin \phi_{0} \hat{\phi} + \cos \theta(\rho) \hat{z}`

有时候公式识别会多出很多无意义仅代表空格的`\,`，同时部分函数会识别为变量名，如`\cos`会识别为`\operatorname{s i n}`，这类问题会对于导入到word产生麻烦。

# 使用环境
版本号：V1.1.1.2
使用环境：Ubuntu+CPU+Pix2Text Serve（服务器端）、Windows+Python（使用端）
服务器配置命令：
`/home/<user_name>/miniconda3/bin/p2t  serve -l en,ch_sim -H 0.0.0.0 -p 8503 -o /home/<user_name>/pix2text --disable-table --enable-formula`
Windows端配置命令：
```
import os
import requests
import pyperclip  # 导入pyperclip库
# 服务器
'http://x.x.x.x:8503/pix2text'
# 指定目录
image_dir = 'C:/test'
# 获取目录中最新的图片文件
latest_image = max([os.path.join(image_dir, f) for f in os.listdir(image_dir) if f.endswith('.png')], key=os.path.getmtime)
# 识别的类型
data = {"file_type": "formula", "resized_shape": 768, "embed_sep": " $,$ ", "isolated_sep": "$$\n, \n$$"}
# 识别的图片配置
files = {"image": (os.path.basename(latest_image), open(latest_image, 'rb'), 'image/jpeg')}
# 开始向服务器 request
r = requests.post(url, data=data, files=files)
outs = r.json()['results']
# 将输出结果复制到剪贴板
pyperclip.copy(outs)
print("输出结果已复制到剪贴板。")
```

**Comment by breezedeus** [comment]
的确有这个问题。不过这是由训练数据导致的。如果你使用时有需要，就只能靠你自己写后处理逻辑做替换了。
