### ISSUE TITLE
Multilingual not working?

### ISSUE THREAD

**Issue by Maissan26** [breezedeus/Pix2Text#148]
Hello I'm quite new to this I tried following the pix2text_v1_1.ipynb. 

When i tried to change the total_config to include a certain language it still uses the original language of the image.

![image](https://github.com/user-attachments/assets/b75c1bc2-d101-4ebe-9183-9b9648bad9f0)

In this case, i change the 'vi' to 'ko'.

Despite that the output is still in Vietnamese. Am I doing something wrong.
Thank you for the time and guidance

**Comment by breezedeus** [comment]
try this:

```python
total_config={
    'text formula': {'languages': ('ko', )}  # you missed ","
}
```

**Comment by Maissan26** [comment]
Thank you for the response, however when I tried changing the config multiple times but it still persist, what I dont understand is when I follow the multilingual it works only on the given image and all other image default to chinese
![image](https://github.com/user-attachments/assets/8a99568a-a8f2-47e2-838e-62023cbeba43)
![image](https://github.com/user-attachments/assets/afcdee77-152b-497e-ae18-55b87318840b)
