### ISSUE TITLE
识别时间过长，如何优化

### ISSUE THREAD

**Issue by 520jefferson** [breezedeus/Pix2Text#149]
模型初始化时的配置：
![image](https://github.com/user-attachments/assets/fa362c3d-cd38-4b6c-a582-d26f378ff4f5)

单个复杂公式识别时间，2分钟了：
![image](https://github.com/user-attachments/assets/34d4438c-fe08-4cde-a97f-f87d88296321)
识别结果：
![image](https://github.com/user-attachments/assets/a031c7d8-b9f6-4521-b1b5-d66d3d5c3749)

途中isolate_formula是一个版面解析判定为公式的结果给到的pix2text去识别的，batchsize=3。请教下，哪个模型用时较长，如何优化？ 还可能是偶现的 @breezedeus 辛苦帮忙分析下

```python
        elif items[1] in ["isolate_formula", "formula_caption","inline_formula", "isolated_formula"]:
                start_time = time.time()
                text = text_formula_ocr.recognize(equation_img, mfr_batch_size=3)
                print("公式时间判定2: ",items[1], "elapse time: ", (time.time() - start_time) * 1000, "ms")
```

**Comment by 520jefferson** [comment]
一般是发生后容易超时
![image](https://github.com/user-attachments/assets/dc5334ee-d70b-4a16-a4b3-6458245ed867)

**Comment by breezedeus** [comment]
是不是把模型导入时间算进去了？。。

**Comment by 520jefferson** [comment]
> 是不是把模型导入时间算进去了？。。
请看我的打印代码，recognize前不会预加载吗？另外，我不止是第一次出现，偶发超时2-3分钟呢
![image](https://github.com/user-attachments/assets/f53ce478-e13d-4bfd-ae77-da2cb41e807a)
