### ISSUE TITLE
cuda errors

### ISSUE THREAD

**Issue by 16131zzzzzzzz** [breezedeus/Pix2Text#18]
>>>from pix2text import Pix2Text
>>>Pix2Text(analyzer_config=dict(model_name='mfd'), device='gpu')
会报错
  File "/home/{username}/.local/lib/python3.7/site-packages/cnstd/yolov7/torch_utils.py", line 90, in select_device
    assert torch.cuda.is_available(), f'CUDA unavailable, invalid device {device} requested'  # check availability
AssertionError: CUDA unavailable, invalid device cuda requested
此时运行torch.is_available()出现False

但如果先import torch并运行torch.is_available()
>>> import torch
>>> torch.cuda.is_available()
True
>>> from pix2text import Pix2Text
>>> self.ocr = Pix2Text(analyzer_config=dict(model_name='mfd'), device='gpu')
这样就不会报错，也可以成功使用gpu

**Comment by breezedeus** [comment]
咦，这个挺奇怪，我找时间看看。

**Comment by breezedeus** [comment]
这是个bug，具体参见： https://github.com/breezedeus/Pix2Text/issues/28 ，CnSTD新版已修复。
