### ISSUE TITLE
try this image

### ISSUE THREAD

**Issue by witchfindertr** [breezedeus/Pix2Text#19]
![Untitled22](https://user-images.githubusercontent.com/12663252/235319923-23a5a1dd-dc82-4357-96c6-045396f55a75.png)

try this image

**Comment by breezedeus** [comment]
<img width="1213" alt="image" src="https://user-images.githubusercontent.com/6712673/235342534-801ff692-6418-469a-9140-e78bd38ec552.png">

yes, the following formulas are not recognized as formulars.
