### ISSUE TITLE
关于recognize函数

### ISSUE THREAD

**Issue by lazi-pr** [breezedeus/Pix2Text#2]
请问作者有没有考虑对recognize函数后续提供可以选择指定识别模型的参数呢，比如如果指定模型如type="formula"那么就选择指定公式模型进行识别，但是如果传入是"none"那么还是以前的自动识别。
因为如下图所示，对于同一个公式我发现如果截图的框选范围不同有时会导致在"**general**"和"**formula**"之间横跳
![QA{ 1`2 JDFSGBC9MUWLS6](https://user-images.githubusercontent.com/86911121/194149681-27b332a0-7118-44f2-89f2-ef03c91afd1e.png)

![9GJFP2%`_6PP%4K61_WV3NI](https://user-images.githubusercontent.com/86911121/194149740-8a27ca78-3ea5-4d6b-94fb-d15f281c7640.png)

**Comment by Alune-233** [comment]
感觉终极办法还是更强力的识别模型（解决左右横跳的阈值

**Comment by breezedeus** [comment]
嗯，是的，还是判断的模型不够准。新版会用新的思路来解决这个问题，到时候再看看效果。

**Comment by breezedeus** [comment]
新版基本不再使用分类模型，这个界面也不再维护了。可以使用 https://p2t.behye.com/https://p2t.behye.com/

**Comment by YingZhuY** [comment]
请问下，刚使用 Pix2Text 新版本中的公式识别，下边是两个 pdf 页面的例子，

![out](https://user-images.githubusercontent.com/53252781/234207683-334db2d3-ea2a-433d-87b8-38caf638a542.png)

![outclear](https://user-images.githubusercontent.com/53252781/234208166-169833ef-df47-47af-aad4-b9bdc9b381f1.png)

对于开启 Analyzer 时识别行内公式和独立行公式

请问下作者，有没有考虑怎样提高行内公式的识别效果

**Comment by breezedeus** [comment]
用更多数据，用更大的模型

**Comment by YingZhuY** [comment]
OK, get. thx
