### ISSUE TITLE
Can I specify or limit the vocabulary set?

### ISSUE THREAD

**Issue by Shadow-Alex** [breezedeus/Pix2Text#23]
Hi, is it possible to restrict the output vocabulary of the model? My output contains some odd symbols, and I'd like to filter them out by limiting or permitting only certain characters.
您好，有办法限制模型的输出词表嘛？我的输出有一些奇怪的符号，我期望通过限制或者只允许特定字符方式将其过滤。

**Comment by breezedeus** [comment]
cnocr是有这个功能的，具体说明可以参考文档：https://cnocr.readthedocs.io/ ， pix2text  是没这个功能的，没法限制latex词表。
