### ISSUE TITLE
How to use custom yolov7-tiny model ckpt for layout analysis.

### ISSUE THREAD

**Issue by Shadow-Alex** [breezedeus/Pix2Text#25]
Hi, I've trained a yolov7 model on my custom dataset, it seems the ckpt used in the package `\.cnstd\1.2\analysis\layout-yolov7_tiny.pt` is somehow different from the output ckpt from the yolov7 training output. Is there any post-process I'm missing?

**Comment by breezedeus** [comment]
Hi, what code did you use to train your model? If it was trained with the code in [breezedeus/yolov7 at dev](https://github.com/breezedeus/yolov7/tree/dev), then you should first use the script [yolov7/export_model.py](https://github.com/breezedeus/yolov7/blob/dev/export_model.py) to transform the model (remove useless params), and then call the model by referring to the usage [here](https://www.breezedeus.com/article/p2t-yolov7-for-zsxq-20230619#f7096a86b7974c3d82f2be47784f6e08).
