### ISSUE TITLE
Bug report when using gpu for Pix2Text.

### ISSUE THREAD

**Issue by Shadow-Alex** [breezedeus/Pix2Text#28]
I think the function `select_device` in `torch_utils.py` only accept `# device = 'cpu' or '0' or '0,1,2,3'` as its valid param.
But the pix2Text passed a 'cuda', which will cause an error in later execution. 
![image](https://github.com/breezedeus/Pix2Text/assets/46802674/2936aae7-8e3a-4a75-a222-33b062380c4e)

A quick fix possible in `pix_to_text.py`: 
![image](https://github.com/breezedeus/Pix2Text/assets/46802674/b493375a-57cb-4ef4-917d-79953de5b569)

**Comment by breezedeus** [comment]
Thanks for the detailed description. I fix the bug in the newest version of CnSTD: v 1.2.3.2, to ensure the consistency of interfaces. Please update CnSTD. https://github.com/breezedeus/CnSTD/blob/master/RELEASE.md

**Comment by Shadow-Alex** [comment]
Thanks for the timely fix!
