### ISSUE TITLE
is it possible to support python3.7?

### ISSUE THREAD

**Issue by unsleepy22** [breezedeus/Pix2Text#31]
currently some dependencies requires python>=3.9, is it possible to support python 3.7 by degrading some of the dependencies? As our company prod env supports python  up to 3.7.

**Comment by unsleepy22** [comment]
maybe by setting these dependencies, the model will work on python3.7?
scipy==1.7.3
scikit-image==0.19.3
numpy==1.21.6

**Comment by breezedeus** [comment]
no idea. Why not try and see what's wrong.
