### ISSUE TITLE
Typo in README?

### ISSUE THREAD

**Issue by xukp20** [breezedeus/Pix2Text#33]
In [this](https://github.com/breezedeus/Pix2Text/blob/main/README.md#%E7%B1%BB%E5%88%9D%E5%A7%8B%E5%8C%96) part, 'analyzer_config' should be **Analyzer模型对应的配置信息** instead of being the same the following 'clf_config'?
See below: 
![图片](https://github.com/breezedeus/Pix2Text/assets/71265541/4f95c1e6-4bf6-463d-842f-31f2a4ed1be2)

**Comment by breezedeus** [comment]
是的，写错了，下次改过来。谢谢。
