### ISSUE TITLE
请问什么时候可以支持PDF中的表格转成markdown的格式？

### ISSUE THREAD

**Issue by cingtiye** [breezedeus/Pix2Text#34]
非常感谢作者开源这么好的项目！
我发现现在公式可以很好的转成markdown的格式，但是PDF中的表格输出还是按照行扫描输出的。Mathpix中的表格输出也是markdown格式。

Pix2Text输入图片为表格，输出为：
Dataset Num.of Avq.# Turns Avq.# Tokens Avq,# Tokens Avq.# Tokens Comoarisons per Dialoaue per Example in Promot in ResponseAnthropic Helpful 122.387 3.0 251.5 17.7 88.4 Anthropic Harmless 43.966 3.0 152.5 15.7 464 0penAl Summarize 176.625 1.0 371.136.0 35.1 0penAl WebGPT 13.333 1.0 237.2 48.3 188.9 StackExchange 1.038.480 1.0 440.2 200.1 240.2 Stanford SHP 74882 1.0 338.3199.5 138.8 Synthetic GPT-J 33,139 1.0 123.3 13,0 110.3 Meta (Safety & Helpfulness 1,418,091 39 798.5 31.4 234.1 Total 2.919,326 1.6595.7 108.2 216.9

Mathpix输入图片为表格，输出为：
| Dataset                     | $\begin{array}{r}\text { Num. of } \\\text { Comparisons }\end{array}$ | $\begin{array}{c}\text { Avg. \# Turns } \\\text { per Dialogue }\end{array}$ | $\begin{array}{c}\text { Avg. \# Tokens } \\\text { per Example }\end{array}$ | $\begin{array}{c}\text { Avg. \# Tokens } \\\text { in Prompt }\end{array}$ | $\begin{array}{c}\text { Avg. \# Tokens } \\\text { in Response }\end{array}$ |
| :-------------------------- | -----------------------------------------------------------: | :----------------------------------------------------------: | :----------------------------------------------------------: | :----------------------------------------------------------: | :----------------------------------------------------------: |
| Anthropic Helpful           |122,387 |  3.0   | 251.5  |  17.7  |  88.4  |
| Anthropic Harmless          | 43,966 |  3.0   | 152.5  |  15.7  |  46.4  |
| OpenAI Summarize            |176,625 |  1.0   | 371.1  | 336.0  |  35.1  |
| OpenAI WebGPT               | 13,333 |  1.0   | 237.2  |  48.3  | 188.9  |
| StackExchange               |                       $1,038,480$ |  1.0   | 440.2  | 200.1  | 240.2  |
| Stanford SHP                | 74,882 |  1.0   | 338.3  | 199.5  | 138.8  |
| Synthetic GPT-J             | 33,139 |  1.0   | 123.3  |  13.0  | 110.3  |
| Meta (Safety & Helpfulness) |                       $1,418,091$ |  3.9   | 798.5  |  31.4  | 234.1  |
| Total                       |                       $2,919,326$ |  1.6   | 595.7  | 108.2  | 216.9  |

**Comment by breezedeus** [comment]
嗯，谢谢。虽然 Pix2Text 目标是朝着版面恢复去的，但是加表格解析应该不会太快。。

**Comment by cingtiye** [comment]
> 嗯，谢谢。虽然 Pix2Text 目标是朝着版面恢复去的，但是加表格解析应该不会太快。。
