### ISSUE TITLE
Improvement plans?

### ISSUE THREAD

**Issue by amrhamedp** [breezedeus/Pix2Text#36]
Hello, 
First I would like to thank you for this really useful tool. I would like to ask if there are plans to :
1-make gui for the script 
2-make pdf to tex similar to mathpix snip

**Comment by breezedeus** [comment]
The general plan is as follows: 
1. this year: continue to optimize the MFD, MFR models, and the text OCR model; 
3. next year: optimize and join the layout analysis model and the table recognition model, so that pix2text can complete the full functionality of the layout recovery.
