### ISSUE TITLE
找不到ConvBNActivation的声明是怎么回事？？

### ISSUE THREAD

**Issue by zongpingding** [breezedeus/Pix2Text#4]
源代码：
```
from pix2text import Pix2Text

img_fp = 'C:/Users/PC/AppData/Local/Programs/Python/Python38/Envs/Pytorch/formula.jpg'
p2t = Pix2Text()
out_text = p2t(img_fp)  # 也可以使用 `p2t.recognize(img_fp)` 获得相同的结果
print(out_text)

```
运行结果：
cannot import name 'ConvBNActivation' from 'torchvision.models.mobilenetv2'
如图：
![image](https://user-images.githubusercontent.com/98604286/198835308-3b4aedac-f3a6-43bd-a5a0-e9f3306bb437.png)
我在其他的文件里边也没有找到它的声明。
注释了这一行之后，它又下载了一些奇怪的东西
运行报错：RuntimeError: stack expects a non-empty TensorList
但是我是用[LaTeX-OCR](https://github.com/lukas-blecher/LaTeX-OCR)的功能都是正常的，就很奇怪？？？

**Comment by breezedeus** [comment]
可能是pytorch和torchvision新版问题，你试试安装这个版本： `pip install torch==1.12.1 torchvision==0.13.1`
