### ISSUE TITLE
Idea: Support more languages

### ISSUE THREAD

**Issue by carminecolucci** [breezedeus/Pix2Text#43]
Are you going to add support for more languages in the future?

**Comment by breezedeus** [comment]
which language do you expect? If you change the text ocr engine, pix2text now can support other languages.

**Comment by carminecolucci** [comment]
Oh okay, thanks. I did not saw anything about support for other languages in the README.

Another thing: since now the English README is the default one, could the output of `p2t predict -h` be translated from Chinese to English as well?

The pypi package still shows a Chinese help message as default.

**Comment by breezedeus** [comment]
> Oh okay, thanks. I did not saw anything about support for other languages in the README.
> 
> Another thing: since now the English README is the default one, could the output of `p2t predict -h` be translated from Chinese to English as well?
> 
> The pypi package still shows a Chinese help message as default.

Good points. I will translate them into english in the next version. Thanks.

**Comment by breezedeus** [comment]
@carminecolucci See the newest version~
