### ISSUE TITLE
pix2text库中serve.py文件找不到set_logger包

### ISSUE THREAD

**Issue by Chenromeo** [breezedeus/Pix2Text#5]
在调用 p2t serve -p 8503时报错，部分报错信息如下：
File "D:\Anaconda3\envs\py38\Lib\site-packages\pix2text\.\serve.py", line 11, in <module>
    from pix2text import set_logger, Pix2Text
ImportError: cannot import name 'set_logger' from 'pix2text' 

去pix2text.py文件里面看了，确实没有set_logger相关的代码

**Comment by Chenromeo** [comment]
在utils.py中找到该函数
继续运行代码报错pix2text.py文件中的Pix2Text类初始化缺少参数，后将该类改为调用pix_to_text.py文件下的Pix2Text类，不再报错；
继续运行p2t serve -p 8503，系统自动下载mobilenet_v2-7ebf99e0.pth文件，但未完成下载即终止，报错如下：
...
File "D:\Anaconda3\envs\py38\Lib\site-packages\pix2text\.\serve.py", line 19, in <module>
    P2T = Pix2Text()
  File "D:\Anaconda3\envs\py38\Lib\site-packages\pix2text\.\pix_to_text.py", line 92, in __init__
    self.image_clf = ImageClassifier(**_clf_config)
...
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
尝试按照模型下载部分建议，单独下载分类模型和LaTeX-OCR的模型文件并放入anaconda虚拟环境中pix2text库中，但依旧报上述错误。
我是通过pip install pix2text安装的p2t相关库，但遇到大量的问题，且安装的库文件和github中的文件存在较大差异，不知道开发者您是否有尝试过通过pip安装您的项目？

**Comment by Chenromeo** [comment]
> 在utils.py中找到该函数 继续运行代码报错pix2text.py文件中的Pix2Text类初始化缺少参数，后将该类改为调用pix_to_text.py文件下的Pix2Text类，不再报错； 继续运行p2t serve -p 8503，系统自动下载mobilenet_v2-7ebf99e0.pth文件，但未完成下载即终止，报错如下： ... File "D:\Anaconda3\envs\py38\Lib\site-packages\pix2text.\serve.py", line 19, in P2T = Pix2Text() File "D:\Anaconda3\envs\py38\Lib\site-packages\pix2text.\pix_to_text.py", line 92, in **init** self.image_clf = ImageClassifier(**_clf_config) ... RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory 尝试按照模型下载部分建议，单独下载分类模型和LaTeX-OCR的模型文件并放入anaconda虚拟环境中pix2text库中，但依旧报上述错误。 我是通过pip install pix2text安装的p2t相关库，但遇到大量的问题，且安装的库文件和github中的文件存在较大差异，不知道开发者您是否有尝试过通过pip安装您的项目？

在linux环境下没遇到相关问题，可以本地使用，但http方式还是会报很多错误

**Comment by breezedeus** [comment]
如果是最新版，是不会找不到 set_logger 的 ，代码：https://github.com/breezedeus/Pix2Text/blob/main/pix2text/__init__.py#L4 ，可能是你的环境有问题。模型没下载完整删了重下就行。
