### ISSUE TITLE
docker部署到python:3.10.13会返回<unused3>

### ISSUE THREAD

**Issue by FocusHuang** [breezedeus/Pix2Text#51]
调用recognize(img, use_analyzer=True)返回json会带<unused3>
{
    "code": 200,
    "message": "OK",
    "data": [
        {
            "type": "embedding",
            "text": " $$\\frac{3}{5}$$ ",
            "position": [
                [
                    205.0,
                    11.0
                ],
                [
                    223.0,
                    11.0
                ],
                [
                    223.0,
                    49.0
                ],
                [
                    205.0,
                    49.0
                ]
            ],
            "line_number": 0
        },
        {
            "position": [
                [
                    586.0,
                    23.0
                ],
                [
                    612.0,
                    23.0
                ],
                [
                    612.0,
                    47.0
                ],
                [
                    586.0,
                    47.0
                ]
            ],
            "type": "text",
            "text": "<unused3>）<unused3>。",
            "line_number": 0
        },
        {
            "position": [
                [
                    12.0,
                    22.0
                ],
                [
                    527.0,
                    22.0
                ],
                [
                    527.0,
                    42.0
                ],
                [
                    12.0,
                    42.0
                ]
            ],
            "type": "text",
            "text": "(<unused3>1<unused3>)<unused3>如<unused3>果<unused3>甲<unused3>数<unused3>是<unused3>乙<unused3>数<unused3>的<unused3>二<unused3>,<unused3>那<unused3>么<unused3>甲<unused3>数<unused3>与<unused3>乙<unused3>数<unused3>的<unused3>最<unused3>简<unused3>整<unused3>数<unused3>比<unused3>是<unused3>(",
            "line_number": 1
        }
    ]
}

**Comment by FocusHuang** [comment]
![image](https://github.com/breezedeus/Pix2Text/assets/20685297/c2ae93f2-52f3-461e-9642-0525632e03db)

**Comment by breezedeus** [comment]
<unused3> 这种格式是预留的字符代号，不是 bug。你可以发下原图我试试。
