### ISSUE TITLE
Handwriting

### ISSUE THREAD

**Issue by Mori-hub** [breezedeus/Pix2Text#55]
Hi Dear,
Really, it is working very well for digital text but about handwriting, there is not any good result, compare with [P2T Online Service](https://p2t.breezedeus.com/)
 1. Digital Text:
 
<img width="701" alt="1008768745_44827076-4" src="https://github.com/breezedeus/Pix2Text/assets/53067774/acaa4a3a-f374-4885-8ae5-9a0f6dacada4">

**Result** 
$$
\eta=\frac{w}{L},\xi=\frac{X}{L},\xi_{s1}=\frac{X_{s1}}{L},\xi_{s2}=\frac{X_{s2}}{L},\xi_{d}=\frac{X_{d}}{L},
$$

 2. Handwriting by Python
 
![Screenshot 2024-01-10 at 12-57-56 CamScanner 01-07-2024 10 22 - 21-33 pdf](https://github.com/breezedeus/Pix2Text/assets/53067774/197fe3d0-84a0-4056-9873-9a3e429f2db3)

**Result** 
$$
{\frac{d\;\rlap{+}\;}{d\;\mathrm{t}}}+\tilde{\mathrm{r}}_{\;\;\;}^{-1}\longrightarrow\left.{\frac{\mathcal{N}c^{2}}{\nu\mathrm{n}}}\;\Xi\right.
$$

 3. Same Image in Online Service
 
**Result** 

$$
\frac{d\overrightarrow{{\mathcal J}}}{d\tau}+\overrightarrow{\tau}_{c}\overrightarrow{{\mathcal J}}\ =\ \frac{\sqrt{e}e^{2}}{m}\overrightarrow{\mathcal E} 
$$

**Comment by breezedeus** [comment]
Thanks. The models used in [P2T Online Service](https://p2t.breezedeus.com/) are more accurate compared to the open source models. A detailed description can be found here: https://www.breezedeus.com/pix2text .
