### ISSUE TITLE
numpy version conflict when pip install pix2text

### ISSUE THREAD

**Issue by typing233** [breezedeus/Pix2Text#56]
problem:C:\Users\typing>pip install numpy==1.24
Collecting numpy==1.24
  Downloading numpy-1.24.0-cp311-cp311-win_amd64.whl (14.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.8/14.8 MB 9.3 MB/s eta 0:00:00
Installing collected packages: numpy
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
onnxruntime 1.16.3 requires numpy>=1.24.2, but you have numpy 1.24.0 which is incompatible.
seaborn 0.13.0 requires numpy!=1.24.0,>=1.20, but you have numpy 1.24.0 which is incompatible.
tensorflow-intel 2.12.0 requires numpy<1.24,>=1.22, but you have numpy 1.24.0 which is incompatible.
Successfully installed numpy-1.24.0

ask:which numpy version should i install, thank you

**Comment by breezedeus** [comment]
``` Successfully installed numpy-1.24.0 ``` 
You have successfully installed it, just use it.
