### ISSUE TITLE
Patterns of incorrect response

### ISSUE THREAD

**Issue by ishan00** [breezedeus/Pix2Text#59]
Hey everyone, I was benchmarking Pix2Text with Mathpix and found the following patterns for which Pix2Text gives incorrect output while Mathpix gives the correct response.

If there are plans for future improvement, please consider this.

1. Greek Symbols
Pix2Text outputs English alphabets instead of Greek in many examples.
- o, a instead of alpha
- B, s instead of beta
- p instead of rho

2. Superscript and Subscript
- 10 m/s2 instead of 10 m/s^2

3. Chemical Compounds
- 15 instead of I3^{-}
- C2HsCI instead of C2H5Cl

**Comment by breezedeus** [comment]
Thanks for sharing. The problems you mentioned should mainly come from the fact that Pix2Text's mathematical formula detection model (MFD) does not detect the corresponding mathematical symbols. We will continue to optimize the accuracy.
