### ISSUE TITLE
请问下分式 和大括号有时候检测不到，是参数不对吗？ 下面是hf-demo测试的结果

### ISSUE THREAD

**Issue by openforward** [breezedeus/Pix2Text#70]
![0a54af7a250d4388c8dae5f0e2554ff5](https://github.com/breezedeus/Pix2Text/assets/66133175/1fb2135f-5294-4ffe-9c0a-0abd34380a6a)
![微信图片_20240305142003](https://github.com/breezedeus/Pix2Text/assets/66133175/999440fe-f5df-4d97-be8c-06ca783927e7)

**Comment by breezedeus** [comment]
应该就是检测模型（MFD）的锅，没检测出来。

**Comment by HanLin-design** [comment]
> 应该就是检测模型（MFD）的锅，没检测出来。

有办法解决吗？

**Comment by breezedeus** [comment]
只能等着模型更新。一种方法就是你自己人工截好图，比如把识别不好的地方手工分成多个部分，多次识别。

**Comment by HanLin-design** [comment]
> 只能等着模型更新。一种方法就是你自己人工截好图，比如把识别不好的地方手工分成多个部分，多次识别。

感谢哈，我试试
