### ISSUE TITLE
请问Paddle和Pix2Text一起使用会报错

### ISSUE THREAD

**Issue by f549263766** [breezedeus/Pix2Text#72]
- device： Ubuntu 22.04， 4GPUS，CUDA Version: 12.0，cudnn8.9
- python3.10，pix2text 1.0.1，paddlepaddle-gpu 2.6.0.post120，torch 2.2.1+cu118，pix2tex 0.1.2
- issue：当单独使用pix2text 时，会报以下提醒，运行时间很长
![image](https://github.com/breezedeus/Pix2Text/assets/44324039/e3ea9bd2-b133-474c-b1f4-1f9d4a63f166)
- issue：当结合paddle使用pix2text时，会报以下错误，`Segmentation fault`
![image](https://github.com/breezedeus/Pix2Text/assets/44324039/2edbd4d4-a8b4-4081-8817-0bb353b7510f)
- issue：当结合paddle使用pix2tex时，正常使用

**Comment by breezedeus** [comment]
看着是 paddle 报的错，我没看出来原因。

**Comment by f549263766** [comment]
我将cudnn升级到9.0后解决该问题
