### ISSUE TITLE
升级pix2text版本为 1.0.2.1，调用curl测试异常,`model_kwargs` are not used by the model

### ISSUE THREAD

**Issue by evanlin88** [breezedeus/Pix2Text#81]
调用命令：curl -F image=@math_test.png --form 'image_type=mixed' --form 'resized_shape=768' http://0.0.0.0:8503/pix2text
异常日志：
[INFO 2024-03-18 11:24:19,559 ocr:56] input params={'resized_shape': 768, 'embed_sep': [' $', '$ '
], 'isolated_sep': ['$$\n', ' \n$$']}
[INFO 2024-03-18 11:24:19,648 _analyze_one:353] Done. (81.2ms) Inference, (1.3ms) NMS

INFO:     127.0.0.1:60744 - "POST /pix2text HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/data/miniconda3/envs/pix2text/lib/python3.10/site-packages/uvicorn/protocols/http/h11_imp
l.py", line 412, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/data/miniconda3/envs/pix2text/lib/python3.10/site-packages/uvicorn/middleware/proxy_heade
rs.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/data/miniconda3/envs/pix2text/lib/python3.10/site-packages/fastapi/applications.py", line
 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/data/miniconda3/envs/pix2text/lib/python3.10/site-packages/starlette/applications.py", li
ne 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/data/miniconda3/envs/pix2text/lib/python3.10/site-packages/starlette/middleware/errors.py
", line 186, in __call__
    raise exc
  File "/data/miniconda3/envs/pix2text/lib/python3.10/site-packages/starlette/middleware/errors.py
", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/data/miniconda3/envs/pix2text/lib/python3.10/site-packages/starlette/middleware/exception
s.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/data/miniconda3/envs/pix2text/lib/python3.10/site-packages/starlette/_exception_handler.p
y", line 64, in wrapped_app
    raise exc
  File "/data/miniconda3/envs/pix2text/lib/python3.10/site-packages/starlette/_exception_handler.p
y", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/data/miniconda3/envs/pix2text/lib/python3.10/site-packages/starlette/routing.py", line 75
8, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/data/miniconda3/envs/pix2text/lib/python3.10/site-packages/starlette/routing.py", line 77
8, in app
    await route.handle(scope, receive, send)
  File "/data/miniconda3/envs/pix2text/lib/python3.10/site-packages/starlette/routing.py", line 29
9, in handle
    await self.app(scope, receive, send)
  File "/data/miniconda3/envs/pix2text/lib/python3.10/site-packages/starlette/routing.py", line 79
, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/data/miniconda3/envs/pix2text/lib/python3.10/site-packages/starlette/_exception_handler.p
y", line 64, in wrapped_app
    raise exc
  File "/data/miniconda3/envs/pix2text/lib/python3.10/site-packages/starlette/_exception_handler.p
y", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/data/miniconda3/envs/pix2text/lib/python3.10/site-packages/starlette/routing.py", line 74
, in app
    response = await func(request)
  File "/data/miniconda3/envs/pix2text/lib/python3.10/site-packages/fastapi/routing.py", line 278,
 in app
    raw_response = await run_endpoint_function(
  File "/data/miniconda3/envs/pix2text/lib/python3.10/site-packages/fastapi/routing.py", line 191,
 in run_endpoint_function
    return await dependant.call(**values)
  File "/data/miniconda3/envs/pix2text/lib/python3.10/site-packages/pix2text-1.0.2.1-py3.10.egg/pi
x2text/serve.py", line 63, in ocr
    res = func(image, **params)
  File "/data/miniconda3/envs/pix2text/lib/python3.10/site-packages/pix2text-1.0.2.1-py3.10.egg/pi
x2text/pix_to_text.py", line 157, in recognize
    out = self.recognize_by_mfd(img, return_text=return_text, **kwargs)
  File "/data/miniconda3/envs/pix2text/lib/python3.10/site-packages/pix2text-1.0.2.1-py3.10.egg/pi
x2text/pix_to_text.py", line 223, in recognize_by_mfd
    mf_results = self.latex_model.recognize(
  File "/data/miniconda3/envs/pix2text/lib/python3.10/site-packages/pix2text-1.0.2.1-py3.10.egg/pi
x2text/latex_ocr.py", line 187, in recognize
    results.extend(self._one_batch(part_imgs, rec_config, **kwargs))
  File "/data/miniconda3/envs/pix2text/lib/python3.10/site-packages/pix2text-1.0.2.1-py3.10.egg/pi
x2text/latex_ocr.py", line 200, in _one_batch
    outs = self.model.generate(
  File "/data/miniconda3/envs/pix2text/lib/python3.10/site-packages/torch/utils/_contextlib.py", l
ine 115, in decorate_context
    return func(*args, **kwargs)
  File "/data/miniconda3/envs/pix2text/lib/python3.10/site-packages/transformers/generation/utils.
py", line 1307, in generate
    self._validate_model_kwargs(model_kwargs.copy())
  File "/data/miniconda3/envs/pix2text/lib/python3.10/site-packages/transformers/generation/utils.
py", line 1122, in _validate_model_kwargs
    raise ValueError(
ValueError: The following `model_kwargs` are not used by the model: ['output_logits'] (note: typos
 in the generate arguments will also show up in this list)

**Comment by breezedeus** [comment]
我这没复现这个问题，你能看看 transformers 的版本号吗？应该要 >=4.37.0

```bash
pip show transformers
```

**Comment by breezedeus** [comment]
不过 serve.py 确实会报一个其他错误，之前版本更新时没改这个文件，之后我改下。

**Comment by ppaanngggg** [comment]
我碰到和 @evanlin88 相同的错误, 错误起因应该是这个参数, 但是如果我去掉这个参数, 后面outs又拿不到logits的结果
 https://github.com/breezedeus/Pix2Text/blob/03f78b6ed8f200475f2782cffbe2f8842d145061/pix2text/latex_ocr.py#L203

我这边的依赖版本如下

```
Package                  Version
------------------------ -----------
aiohttp                  3.9.3
aiosignal                1.3.1
appdirs                  1.4.4
async-timeout            4.0.3
attrs                    23.2.0
certifi                  2024.2.2
charset-normalizer       3.3.2
click                    8.1.7
cmake                    3.28.3
cnocr                    2.3.0.1
cnstd                    1.2.3.5
coloredlogs              15.0.1
contourpy                1.2.0
cycler                   0.12.1
datasets                 2.17.0
dill                     0.3.8
docker-pycreds           0.4.0
easyocr                  1.7.1
evaluate                 0.4.1
filelock                 3.13.1
flatbuffers              23.5.26
fonttools                4.49.0
frozenlist               1.4.1
fsspec                   2023.10.0
gitdb                    4.0.11
GitPython                3.1.42
huggingface-hub          0.20.3
humanfriendly            10.0
idna                     3.6
imageio                  2.34.0
importlib-resources      6.1.1
Jinja2                   3.1.3
kiwisolver               1.4.5
lazy_loader              0.3
lightning-utilities      0.10.1
lit                      18.1.1
MarkupSafe               2.1.5
matplotlib               3.8.3
mpmath                   1.3.0
multidict                6.0.5
multiprocess             0.70.16
networkx                 3.2.1
ninja                    1.11.1.1
numpy                    1.26.4
nvidia-cublas-cu11       11.10.3.66
nvidia-cuda-cupti-cu11   11.7.101
nvidia-cuda-nvrtc-cu11   11.7.99
nvidia-cuda-runtime-cu11 11.7.99
nvidia-cudnn-cu11        8.5.0.96
nvidia-cufft-cu11        10.9.0.58
nvidia-curand-cu11       10.2.10.91
nvidia-cusolver-cu11     11.4.0.1
nvidia-cusparse-cu11     11.7.4.91
nvidia-nccl-cu11         2.14.3
nvidia-nvtx-cu11         11.7.91
onnx                     1.15.0
onnxruntime              1.17.0
opencv-python            4.9.0.80
opencv-python-headless   4.9.0.80
optimum                  1.16.2
packaging                23.2
pandas                   2.2.0
pillow                   10.2.0
pip                      23.3.2
Polygon3                 3.0.9.1
protobuf                 4.25.3
psutil                   5.9.8
pyarrow                  15.0.0
pyarrow-hotfix           0.6
pyclipper                1.3.0.post5
pyparsing                3.1.1
python-bidi              0.4.2
python-dateutil          2.8.2
pytorch-lightning        2.2.0.post0
pytz                     2024.1
PyYAML                   6.0.1
regex                    2023.12.25
requests                 2.31.0
responses                0.18.0
safetensors              0.4.2
scikit-image             0.22.0
scipy                    1.12.0
seaborn                  0.13.2
sentencepiece            0.1.99
sentry-sdk               1.40.4
setproctitle             1.3.3
setuptools               69.0.3
shapely                  2.0.2
six                      1.16.0
smmap                    5.0.1
sympy                    1.12
tifffile                 2024.2.12
tokenizers               0.15.2
torch                    2.0.1
torchmetrics             1.3.1
torchvision              0.15.2
tqdm                     4.66.2
transformers             4.37.2
triton                   2.0.0
typing_extensions        4.9.0
tzdata                   2024.1
Unidecode                1.3.8
urllib3                  2.2.0
wandb                    0.16.3
wheel                    0.42.0
xxhash                   3.4.1
yarl                     1.9.4
zipp                     3.17.0
```

**Comment by evanlin88** [comment]
> 我这没复现这个问题，你能看看 transformers 的版本号吗？应该要 >=4.37.0
> 
> ```shell
> pip show transformers
> ```

(pix2text) root@ai-1:/data/pix2text# pip show transformers
Name: transformers
Version: 4.37.2

-- 版本没问题，主要是针对http服务异常，我验证的是http服务，哈；目前我先回退到v1.0.1才正常；v1.0.2.1和v1.0.2都不行

**Comment by evanlin88** [comment]
> 我碰到和 @evanlin88 相同的错误, 错误起因应该是这个参数, 但是如果我去掉这个参数, 后面outs又拿不到logits的结果
> 
> https://github.com/breezedeus/Pix2Text/blob/03f78b6ed8f200475f2782cffbe2f8842d145061/pix2text/latex_ocr.py#L203
> 
> 我这边的依赖版本如下
> 
> ```
> Package                  Version
> ------------------------ -----------
> aiohttp                  3.9.3
> aiosignal                1.3.1
> appdirs                  1.4.4
> async-timeout            4.0.3
> attrs                    23.2.0
> certifi                  2024.2.2
> charset-normalizer       3.3.2
> click                    8.1.7
> cmake                    3.28.3
> cnocr                    2.3.0.1
> cnstd                    1.2.3.5
> coloredlogs              15.0.1
> contourpy                1.2.0
> cycler                   0.12.1
> datasets                 2.17.0
> dill                     0.3.8
> docker-pycreds           0.4.0
> easyocr                  1.7.1
> evaluate                 0.4.1
> filelock                 3.13.1
> flatbuffers              23.5.26
> fonttools                4.49.0
> frozenlist               1.4.1
> fsspec                   2023.10.0
> gitdb                    4.0.11
> GitPython                3.1.42
> huggingface-hub          0.20.3
> humanfriendly            10.0
> idna                     3.6
> imageio                  2.34.0
> importlib-resources      6.1.1
> Jinja2                   3.1.3
> kiwisolver               1.4.5
> lazy_loader              0.3
> lightning-utilities      0.10.1
> lit                      18.1.1
> MarkupSafe               2.1.5
> matplotlib               3.8.3
> mpmath                   1.3.0
> multidict                6.0.5
> multiprocess             0.70.16
> networkx                 3.2.1
> ninja                    1.11.1.1
> numpy                    1.26.4
> nvidia-cublas-cu11       11.10.3.66
> nvidia-cuda-cupti-cu11   11.7.101
> nvidia-cuda-nvrtc-cu11   11.7.99
> nvidia-cuda-runtime-cu11 11.7.99
> nvidia-cudnn-cu11        8.5.0.96
> nvidia-cufft-cu11        10.9.0.58
> nvidia-curand-cu11       10.2.10.91
> nvidia-cusolver-cu11     11.4.0.1
> nvidia-cusparse-cu11     11.7.4.91
> nvidia-nccl-cu11         2.14.3
> nvidia-nvtx-cu11         11.7.91
> onnx                     1.15.0
> onnxruntime              1.17.0
> opencv-python            4.9.0.80
> opencv-python-headless   4.9.0.80
> optimum                  1.16.2
> packaging                23.2
> pandas                   2.2.0
> pillow                   10.2.0
> pip                      23.3.2
> Polygon3                 3.0.9.1
> protobuf                 4.25.3
> psutil                   5.9.8
> pyarrow                  15.0.0
> pyarrow-hotfix           0.6
> pyclipper                1.3.0.post5
> pyparsing                3.1.1
> python-bidi              0.4.2
> python-dateutil          2.8.2
> pytorch-lightning        2.2.0.post0
> pytz                     2024.1
> PyYAML                   6.0.1
> regex                    2023.12.25
> requests                 2.31.0
> responses                0.18.0
> safetensors              0.4.2
> scikit-image             0.22.0
> scipy                    1.12.0
> seaborn                  0.13.2
> sentencepiece            0.1.99
> sentry-sdk               1.40.4
> setproctitle             1.3.3
> setuptools               69.0.3
> shapely                  2.0.2
> six                      1.16.0
> smmap                    5.0.1
> sympy                    1.12
> tifffile                 2024.2.12
> tokenizers               0.15.2
> torch                    2.0.1
> torchmetrics             1.3.1
> torchvision              0.15.2
> tqdm                     4.66.2
> transformers             4.37.2
> triton                   2.0.0
> typing_extensions        4.9.0
> tzdata                   2024.1
> Unidecode                1.3.8
> urllib3                  2.2.0
> wandb                    0.16.3
> wheel                    0.42.0
> xxhash                   3.4.1
> yarl                     1.9.4
> zipp                     3.17.0
> ```

本来我也想计划将参数output_logits修改成false，但还是先回退版本试试，发现v1.0.1才正常；v1.0.2.1和v1.0.2都不行

**Comment by breezedeus** [comment]
应该是 transformers<=4.37.2 不支持这个参数。。大家把 transformers 更新到 >=4.38.0 就行。

**Comment by ppaanngggg** [comment]
> 应该是 transformers<=4.37.2 不支持这个参数。。大家把 transformers 更新到 >=4.38.0 就行。

测试了一下确实是, 那麻烦您把requirements.txt里面的transformers版本更新下

**Comment by breezedeus** [comment]
> > 应该是 transformers<=4.37.2 不支持这个参数。。大家把 transformers 更新到 >=4.38.0 就行。
> 
> 测试了一下确实是, 那麻烦您把requirements.txt里面的transformers版本更新下

已发新版修复这个兼容性问题。大家也可以通过安装新版来修复：

```bash
pip install pix2text==1.0.2.2 -i https://pypi.org/simple
```

**Comment by evanlin88** [comment]
> > > 应该是 transformers<=4.37.2 不支持这个参数。。大家把 transformers 更新到 >=4.38.0 就行。
> > 
> > 
> > 测试了一下确实是, 那麻烦您把requirements.txt里面的transformers版本更新下
> 
> 已发新版修复这个兼容性问题。大家也可以通过安装新版来修复（transformers 就不用更新到 4.38.0 以上了）：
> 
> ```shell
> pip install pix2text==1.0.2.2 -i https://pypi.org/simple
> ```

已验证，没问题了，是transformers版本影响
