### ISSUE TITLE
List index out of range when recognizing some images

### ISSUE THREAD

**Issue by zfy1041264242** [breezedeus/Pix2Text#84]
File "/remote-home/cs_acmis_sdtw/latex/Model_test/Pdf_ocr.py", line 81, in png_to_text
    outs = p2t.recognize(img_fp, resized_shape=608, return_text=True)  # 也可以使用 `p2t(img_fp)` 获得相同的结果
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/remote-home/cs_acmis_sdtw/latex/Pix2Text/pix2text/pix_to_text.py", line 157, in recognize
    out = self.recognize_by_mfd(img, return_text=return_text, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/remote-home/cs_acmis_sdtw/latex/Pix2Text/pix2text/pix_to_text.py", line 350, in recognize_by_mfd
    outs = merge_line_texts(
           ^^^^^^^^^^^^^^^^^
  File "/remote-home/cs_acmis_sdtw/latex/Pix2Text/pix2text/utils.py", line 726, in merge_line_texts
    out_texts[line_number].append(cur_text)
IndexError: list index out of range

**Comment by breezedeus** [comment]
看看 pix2text 的版本号，如果不是最新的就更新到最新版

**Comment by zfy1041264242** [comment]
After I tried updating to the latest version, I still get the above error when recognizing certain images.

**Comment by zfy1041264242** [comment]
![cropped_text_0](https://github.com/breezedeus/Pix2Text/assets/112854533/e3db1a16-b9ce-46f5-8deb-15e5e963b23d)
Here's a picture of what went wrong。
Here's the picture of what went wrong, I just made a simple call：
def png_to_text(img_fp):
    p2t = Pix2Text()
    outs = p2t.recognize(img_fp, resized_shape=608, return_text=True)  
    return outs

**Comment by breezedeus** [comment]
The bug has been reproduced, thanks much. I will release a new version to fix it asap.

**Comment by shantzhou** [comment]
> 看看 pix2text 的版本号，如果不是最新的就更新到最新版

更新到最新会报这个错

**Comment by shantzhou** [comment]
> 看看 pix2text 的版本号，如果不是最新的就更新到最新版
我已定位到问题，
这个操作会把空字符滤掉，如果没有识别出来的框，会强行去掉。你后面的后处理索引又用到了linenumer来索引 导致出错。
outs[line_idx] = [box for box in line_boxes if box['text'].strip()]

**Comment by breezedeus** [comment]
This issue has been fixed in the new version `v1.0.2.3`. Thanks.
