### ISSUE TITLE
YoloV7_Tiny 自动下载失败

### ISSUE THREAD

**Issue by xiehurricane** [breezedeus/Pix2Text#87]
YoloV7_Tiny 自动下载失败

[WARNING 2024-04-07 17:15:53,577 _assert_and_prepare_model_files:214] Can NOT find model file C:\Users\Administrator\AppData\Roaming\cnstd\1.2\analysis\mfd-yolov7_tiny.pt 
[ERROR 2024-04-07 17:15:53,917 get_model_file:251] Failed downloading url https://sg-models.oss-cn-beijing.aliyuncs.com/cnstd/1.2/yolov7_tiny_mfd-pytorch.zip 

pix2text=1.0.2.3

**Comment by breezedeus** [comment]
嗯，oss 失效不能自动下载模型了。https://github.com/breezedeus/CnSTD?tab=readme-ov-file#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95 参考这里的说明和百度云下载链接手动下载吧。
