### ISSUE TITLE
failed to download the models through cn oss

### ISSUE THREAD

**Issue by vandermondeDET** [breezedeus/Pix2Text#88]
I have solved it mostly, though I have to make a warning for others' convenience:
when first using pix2text and automatically downloading models, whether cnocr or cnstd used the url like https://[c/cnstd/1.2/ch_PP-OCRv3_det_infer-onnx.zip](https://sg-models.oss-cn-beijing.aliyuncs.com/cnstd/1.2/ch_PP-OCRv3_det_infer-onnx.zip). However, the author of the pip libs cnocr and cnstd had warned in github that cn oss cannot be used just now. Downloading path must be swithed to hf rather than cn. 
So after upgrading cnstd and cnocr these two python libs, most tasks could continue, though the pix2text models still cannot download as using https://[sg-models.oss-cn-beijing.aliyuncs.com/.
Wish the author can better solve it.
Thanks

**Comment by vandermondeDET** [comment]
I cannot find how to download pix2text free models without cn oss now

**Comment by vandermondeDET** [comment]
<img width="594" alt="image" src="https://github.com/breezedeus/Pix2Text/assets/156590165/1fc5fcf0-dc6a-469e-93b0-dda7c91c3838">

**Comment by breezedeus** [comment]
Hi, the oss downloads are deprecated, please update cnstd and cnocr to the latest versions, and then try again:

```bash
pip install cnstd==1.2.3.6 cnocr==2.3.0.2 -i https://pypi.org/simple
```
