### ISSUE TITLE
可否告知免费版模型训练数据量级

### ISSUE THREAD

**Issue by ManiiXu** [breezedeus/Pix2Text#89]
对于公式识别任务（MFR），免费版模型较later_ocr有明显的效果提升，可否方便告知模型在训练时大约用了多少量级的数据量？
以及免费版和收费版的差异在什么？是模型更大了还是用的数据更多了？

**Comment by breezedeus** [comment]
基础模型的训练数据大概是 2M，付费版的训练数据里包含了一些 P2T 用户真实上传的图片。模型是一样大的，只是训练数据更多。
