### ISSUE TITLE
 ParseError

### ISSUE THREAD

**Issue by liuhuan-gl** [breezedeus/Pix2Text#91]
请问使用md打开公式识别渲染结果时，出现了这个问题，这种问题该如何解决呢，谢谢
 ParseError: KaTeX parse error: Expected group as argument to '\.' at end of input: …xi_{\bar{z}} \.

**Comment by liuhuan-gl** [comment]
> 说明这个对应的 Latex 表达式有问题。手动修复，或者扔给 ChatGPT 修复。

请问是不是md中是katex标准，而模型输出是latex标准的原因

**Comment by breezedeus** [comment]
应该不是。你可以把结果粘到 https://p2t.breezedeus.com/ 看看能不能渲染。如果不能就是这个识别结果本身有问题。有些识别结果的确会有问题，但不是很常见。
